### PR TITLE
log login errors for fail2ban

### PR DESCRIPTION
**Pull request by Rico29**
#67

### CODE REVIEW

**Comment by Rico29** [comment]
do I have to put the logfile path to a configrable variable ?

**Comment by loewexy** [comment]
I am not shure if it would be better to use a seperate log file instead. I am currently at a rewrite of the software so I wont merge that change, but I will leave the issue open as it seems to be a good idea.

**Comment by Rico29** [comment]
Hello
Separate log file ? is there an existing one filled by pdns-manager ?

2018-02-13 10:23 GMT+01:00 Lukas Metzger <notifications@github.com>:

**Comment by loewexy** [comment]
No currently there is no existing logfile. But if I understood correctly you are posting the messages to the apache error log. Maybe it would be an better option to write a separate logfile for PDNS Manager...

**Comment by HendrikF** [comment]
Hey, I have to intervene here. This PR adds no additional security at all! :warning:

As the logging is initiated from the client side, it can be disabled by an attacker.
(In fact, attackers would send login requests directly to api/index.php without using the actual login form.)

The only place, where this logging would help is at api/index.php, where the actual login request is processed.

**Comment by loewexy** [comment]
You are definitely right... in the current version the code is completely useless. I did not review the code as I am currently reimplementing complete pdnsmanager, thus the PR is not really needed. But I let the issue open to implement it in a new version.

**Comment by HendrikF** [comment]
It's cool that you want to reimplement it. This feature is really worth to be implemented in the next version.

**Comment by loewexy** [comment]
The logging in version 2.0 should be sufficent for this purpose. If not you can then open a new issue.

**Pull request closed without merging**
