### PR TITLE
Support for Mysql access using sockets

### PR DESCRIPTION
**Pull request by MichaelSp**
I had to add support for sockets as my sockets where not in the default location. Maybe you want to add this in order to have a common location to change the socket location.

### CODE REVIEW

**Comment by loewexy** [comment]
It would be good to fix this. But I would prefer a solution with the existing config-file. Why is is not possible to set the setting there?

**Comment by MichaelSp** [comment]
The idea was to not load the $config stuff into api/install when it's not required. But it's not a big difference. So I'll move it to the config-file.

**Comment by loewexy** [comment]
Okay now I understand what is done here. My suggestion would be to make a Config option $config['db_socket']  and use this in database.php to make the setting.

To use the default we can use either not setting the variable or setting it to NULL in config-default.php. This would be cleaner and more consistent.

**Comment by MichaelSp** [comment]
Tried that. Strange but that didn't work for me?!

**Comment by loewexy** [comment]
This seems very strange, this should definitely work. If it is set before the connection is attempted.
Currently I have no time to build a test setup and write a fix, if you can't do maybe I will do it later.

**Pull request closed without merging**
