### PR TITLE
Add support for postgresql

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Comment by genofire** [comment]
```
postgres[21018]: 2019-03-28 08:03:18.298 CET [31866] ERROR:  syntax error at or near "E" at character 21
postgres[21018]: 2019-03-28 08:03:18.298 CET [31866] STATEMENT:
postgres[21018]:                     DELETE E FROM remote E
postgres[21018]:                     LEFT OUTER JOIN records R ON R.id=E.record
postgres[21018]:                     WHERE R.domain_id=$1
```

**Comment by genofire** [comment]
close without comment?
i could believe it is already fixed ....

**Comment by loewexy** [comment]
I could not determine what the state of the PR was. It looks to me like there are still errors and no progress so far. If this is not the case please correct me and tell me what the state ist.

**Comment by genofire** [comment]
wow this patch still works over 2.1.0 .... nice

**Comment by mrblumi** [comment]
@genofire Did you manage to fix to postgresql syntax error you mentioned several years ago? I'd love to see a functional postgresql version of this...

**Comment by genofire** [comment]
i have not take look in my logs again (at that time, it was not reproducible for me) ... but it still run and works (i only use powerdns as master, slaves are nsd ...). But i am migrating away ...

**Pull request closed without merging**
